name: weather_app
description: A new Flutter application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  geolocator: ^5.3.1
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.2+1
  intl: ^0.16.1
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    
  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: WeatherIcons
    fonts:
    - asset: fonts/weathericons-regular.ttf
